---
title: ''
output:
  html_document: default
  pdf_document: default
date: '2022-05-02'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(patchwork)
library(scales)
library(ggridges)

data <- read_tsv(file = "../data/03_nhgh_clean_aug.tsv")
```


# Barplots of people diagnosed with diabetes, divided on treatment status

##Data treatment for plots
```{r}
data_dx <- data %>% 
  filter(dx == 1)
```

##Barplot of treated vs. non-treated
```{r}
ggplot(data = data_dx, 
       mapping = aes(x = `Treatment status`, 
                     fill = `Treatment status`)) + 
  geom_bar() +
  labs(title = "Distribution of diabetes mellitus patients",
       subtitle = "Based on treatment or no treatment",
       y = "Count of patients") +
  theme(legend.position = "none")
```


##Stratify on income groups and ethnicity
```{r}
dx_total <- data %>% 
  filter(dx == 1) %>% 
  mutate(`Treatment` = case_when(
    tx == 0 ~ "Not Treated",
    tx == 1 ~ "Treated"),
    Income_level = case_when(
      income <= 10000 ~ "Income: <10.000",
      income > 10000 & income <= 25000 ~ "Income: ]10.000;25.000]",
      income > 25000 & income <= 50000 ~ "Income: ]25.000;50.000]",
      income > 50000 & income <= 75000 ~ "Income: ]50.000;75.000]",
      income > 75000 ~ "Income: >75.000"
    ))
```

```{r}
ggplot(data = dx_total, 
       mapping = aes(x = age,
                     y = Income_level,
                     fill = `Treatment`)) +
  geom_density_ridges(alpha = 0.5, scale = 0.95) + 
  theme_minimal(base_family = "Avenir") +
  geom_vline(xintercept = 52, linetype = "dotted") + 
  geom_vline(xintercept = 63, linetype = "dotted") + 
  theme(plot.title = element_text(hjust = 1, vjust=0),
        legend.position = "bottom") +
  labs(title = "Distribution of people diagnosed with Diabetes Mellitus",
       x = "Age",
       y = "Income group") 
```

```{r}
ggplot(data = dx_total, 
       mapping = aes(x = age,
                     y = re,
                     fill = `Treatment`)) +
  geom_density_ridges(alpha = 0.5, scale = 0.95) + 
  theme_minimal(base_family = "Avenir") +
  geom_vline(xintercept = 52, linetype = "dotted") + 
  geom_vline(xintercept = 63, linetype = "dotted") + 
  theme(plot.title = element_text(hjust = 1, vjust=0),
        legend.position = "bottom") +
  labs(title = "Distribution of people diagnosed with Diabetes Mellitus",
       x = "Age",
       y = "Ethnicity") 
```




##Analyses investigating serum albumin
```{r}
ggplot(data = data,
       mapping = aes(x = albumin, 
                     y = `BMI category`,
                     fill = `BMI category`)) +
  geom_boxplot()



data <- data %>% 
  mutate(`BMI class` = case_when(bmi < 18.5 
                                 ~ "Underweight",
                               18.5 <= bmi & bmi < 25.0 
                               ~ "Normal weight",
                               25.0 <= bmi & bmi < 30.0 
                               ~ "Overweight",
                               30.0 <= bmi & bmi < 35.0 
                               ~ "Obese",
                               35.0 <= bmi & bmi < 40.0 
                               ~ "Severe obesity",
                               40.0 <= bmi & bmi < 50.0 
                               ~ "Morbid obesity",
                               50.0 <= bmi ~ 
                                 "Super obese"),
         `BMI class` = factor(`BMI class`, levels = 
                                c("Underweight",
                                  "Normal weight",
                                  "Overweight",
                                  "Obese",
                                  "Severe obesity",
                                  "Morbid obesity",
                                  "Super obese")),
         diagnosed = case_when(dx == 0 ~ "Not diagnosed",
                               dx == 1 ~ "Diagnosed"))
#Maybe fix title??
ggplot(data = data,
       mapping = aes(x = albumin, 
                     y = `BMI class`,
                     fill = `BMI class`)) +
  geom_boxplot() +
  labs(title = "Distributions of Albumin levels based on BMI class",
       x = "Albumin (g/dL)")


#Density plot of albumin based on diagnosis
ggplot(data = data,
       mapping = aes(x = albumin,
                     color = diagnosed)) + 
  geom_density() + 
  labs(x = "Albumin (g/dL)",
       y = "Density",
       title = "Distribution of Albumin levels",
       subtitle = "Divided into diagnosed and not diagnosed with diabetes mellitus") +
  theme(legend.position = "bottom",
        legend.title = element_blank())


#Density plot of albumin based on gender
ggplot(data = data,
       mapping = aes(x = albumin,
                     color = gender)) + 
  geom_density() + 
  labs(x = "Albumin (g/dL)",
       y = "Density",
       title = "Distribution of Albumin levels",
       subtitle = "Divided by gender") +
  theme(legend.position = "bottom",
        legend.title = element_blank())

#Barplot of distribution of diagnosis in genders
ggplot(data = data,
       mapping = aes(x = gender,
                     fill = diagnosed)) + 
  geom_bar(alpha = 0.8) +
  theme(legend.position = "bottom",
        legend.title = element_blank()) +
  labs(title = "Distribution of people diagnosed with diabetes mellitus",
       subtitle = "Divided into gender",
       x = "Gender",
       y = "Number of individuals")


#Due to the relation between diagnosis, gender and albumin levels,
#we test boxplots over BMI distributions for genders

ggplot(data = data,
       mapping = aes(x = gender,
                     fill = `BMI class`)) +
  geom_bar(position = "dodge") +
  labs(x = "Gender",
       y = "Count of people")

```

